spring.application.name=tienda

spring.datasource.url=jdbc:postgresql://localhost:5432/tienda_backend
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD_POSTGRE}
spring.datasource.driver-class=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

